services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: orderflow-php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:8000"
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: orderflow-worker
    working_dir: /var/www/html
    command: php bin/console messenger:consume async -vv --time-limit=3600 --memory-limit=256M
    volumes:
      - ./:/var/www/html
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  outbox_publisher:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: orderflow-outbox-publisher
    working_dir: /var/www/html
    command: php bin/console app:outbox:publish --loop --limit=50 --sleep-ms=1000
    volumes:
      - ./:/var/www/html
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  database:
    image: postgres:16
    container_name: orderflow-postgres
    environment:
      POSTGRES_DB: orderflow
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d orderflow"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: orderflow-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  pg_data:
