<?php

declare(strict_types=1);

namespace App\Domain\Order\Enum;

enum OrderEventName: string
{
    case ORDER_CREATED = 'ORDER_CREATED';
    case INVENTORY_RESERVED = 'INVENTORY_RESERVED';
    case INVENTORY_RESERVATION_FAILED = 'INVENTORY_RESERVATION_FAILED';
    case PAYMENT_APPROVED = 'PAYMENT_APPROVED';
    case PAYMENT_REJECTED = 'PAYMENT_REJECTED';
    case ORDER_CONFIRMED = 'ORDER_CONFIRMED';
    case NOTIFICATION_SENT = 'NOTIFICATION_SENT';
    case NOTIFICATION_FAILED = 'NOTIFICATION_FAILED';
}
